import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/layout/Header";
import { ReactLenis } from "lenis/react";
import CTAButton from "@/components/ui/CTAButton";
// import Cursor from "../components/ui/Cursor";
import { saans } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${saans.className} antialiased bg-neutral-100 text-neutral-900 overscroll-none`}
        >
          {/* <Header /> */}
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
