import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/layout/Header";
import { ReactLenis } from "lenis/react";
import CTAButton from "@/components/ui/CTAButton";
import { ViewTransitions } from "next-view-transitions";
import { saans } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <ReactLenis root>
          <body
            className={`${saans.className} antialiased bg-neutral-100 text-neutral-900 overscroll-none`}
          >
            <Header />
            <CTAButton />
            {children}
          </body>
        </ReactLenis>
      </html>
    </ViewTransitions>  
  );
}
